// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var ApolloLinks = require("reason-apollo/lib/js/src/ApolloLinks.bs.js");
var ReasonApollo = require("reason-apollo/lib/js/src/ReasonApollo.bs.js");
var ApolloInMemoryCache = require("reason-apollo/lib/js/src/ApolloInMemoryCache.bs.js");

var inMemoryCache = ApolloInMemoryCache.createInMemoryCache(/* Some */[(function (obj) {
          return obj.id;
        })], /* None */0, /* () */0);

var httpLink = ApolloLinks.createHttpLink("http://localhost:4000", /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* () */0);

var instance = ReasonApollo.createApolloClient(httpLink, inMemoryCache, /* None */0, /* None */0, /* None */0, /* None */0, /* () */0);

exports.inMemoryCache = inMemoryCache;
exports.httpLink = httpLink;
exports.instance = instance;
/* inMemoryCache Not a pure module */
