// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Utils = require("../Utils.js");
var React = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var CreatePostButton = require("../components/CreatePostButton.js");

function handleClick(href, $$event) {
  if ($$event.defaultPrevented) {
    return 0;
  } else {
    $$event.preventDefault();
    return ReasonReact.Router[/* push */0](href);
  }
}

function reducer(action, state) {
  if (action.tag) {
    return /* Update */Block.__(0, [/* record */[
                /* title */state[/* title */0],
                /* text */action[0]
              ]]);
  } else {
    return /* Update */Block.__(0, [/* record */[
                /* title */action[0],
                /* text */state[/* text */1]
              ]]);
  }
}

function initialState() {
  return /* record */[
          /* title */"",
          /* text */""
        ];
}

function onTextInputChange(param, e) {
  return Curry._1(param[/* send */3], /* ChangeText */Block.__(1, [e.target.value]));
}

function onTitleInputChange(param, e) {
  return Curry._1(param[/* send */3], /* ChangeTitle */Block.__(0, [e.target.value]));
}

var component = ReasonReact.reducerComponent("CreatePost");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      return React.createElement("div", {
                  className: "pa4 flex justify-center bg-white"
                }, React.createElement("form", undefined, React.createElement("h1", undefined, Utils.ste("Create Draft")), React.createElement("input", {
                          className: "w-100 pa2 mv2 br2 b--black-20 bw1",
                          autoFocus: /* true */1,
                          placeholder: "Title",
                          required: /* true */1,
                          type: "text",
                          value: self[/* state */1][/* title */0],
                          onChange: (function (param) {
                              return onTitleInputChange(self, param);
                            })
                        }), React.createElement("textarea", {
                          className: "db w-100 ba bw1 b--black-20 pa2 br2 mb2",
                          cols: 50,
                          placeholder: "Content",
                          required: /* true */1,
                          rows: 8,
                          type: "text",
                          value: self[/* state */1][/* text */1],
                          onChange: (function (param) {
                              return onTextInputChange(self, param);
                            })
                        }), ReasonReact.element(/* None */0, /* None */0, CreatePostButton.make(self[/* state */1][/* text */1], self[/* state */1][/* title */0], /* array */[])), React.createElement("a", {
                          className: "f6 pointer",
                          onClick: (function ($$event) {
                              return handleClick("/", $$event);
                            })
                        }, Utils.ste(" or cancel"))));
    });
  newrecord[/* initialState */10] = initialState;
  newrecord[/* reducer */12] = reducer;
  return newrecord;
}

exports.handleClick = handleClick;
exports.reducer = reducer;
exports.initialState = initialState;
exports.onTextInputChange = onTextInputChange;
exports.onTitleInputChange = onTitleInputChange;
exports.component = component;
exports.make = make;
/* component Not a pure module */
