// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("../Utils.js");
var React = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Error");

function make(value, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "flex w-100 h-100 items-center justify-center pt7"
                }, React.createElement("div", undefined, Utils.ste("An unexpected error occured.")), value ? Utils.ste(value[0]) : null);
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
