// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("../Utils.js");
var React = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var loading = /* :: */[
  "flex w-100 h-100 items-center justify-center pt7",
  /* [] */0
];

var component = ReasonReact.statelessComponent("NotFound");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: Utils.makeCls(loading)
                }, React.createElement("div", undefined, Utils.ste("Page Not Found ...")));
    });
  return newrecord;
}

exports.loading = loading;
exports.component = component;
exports.make = make;
/* component Not a pure module */
