// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");

function makeCls(x) {
  return Belt_List.reduce(x, "", (function (a, b) {
                return a + (" " + b);
              }));
}

function ste(prim) {
  return prim;
}

exports.makeCls = makeCls;
exports.ste = ste;
/* No side effect */
