// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Nav = require("./Nav.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var FeedPage = require("../pages/FeedPage.js");
var NotFound = require("../pages/NotFound.js");
var CreatePage = require("../pages/CreatePage.js");
var DetailPage = require("../pages/DetailPage.js");
var DraftsPage = require("../pages/DraftsPage.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

function reducer(action, _) {
  return /* Update */Block.__(0, [/* record */[/* route */action[0]]]);
}

function routeFromUrl(url) {
  var match = url[/* path */0];
  if (match) {
    switch (match[0]) {
      case "/" : 
          if (match[1]) {
            return /* NotFound */2;
          } else {
            return /* FeedPage */0;
          }
      case "create" : 
          if (match[1]) {
            return /* NotFound */2;
          } else {
            return /* CreatePage */3;
          }
      case "drafts" : 
          if (match[1]) {
            return /* NotFound */2;
          } else {
            return /* DraftsPage */1;
          }
      case "post" : 
          var match$1 = match[1];
          if (match$1 && !match$1[1]) {
            return /* DetailPage */[match$1[0]];
          } else {
            return /* NotFound */2;
          }
      default:
        return /* NotFound */2;
    }
  } else {
    return /* FeedPage */0;
  }
}

var component = ReasonReact.reducerComponent("App");

function ste(prim) {
  return prim;
}

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      var match = self[/* state */1][/* route */0];
      var tmp;
      if (typeof match === "number") {
        switch (match) {
          case 0 : 
              tmp = ReasonReact.element(/* None */0, /* None */0, FeedPage.make(/* array */[]));
              break;
          case 1 : 
              tmp = ReasonReact.element(/* None */0, /* None */0, DraftsPage.make(/* array */[]));
              break;
          case 2 : 
              tmp = ReasonReact.element(/* None */0, /* None */0, NotFound.make(/* array */[]));
              break;
          case 3 : 
              tmp = ReasonReact.element(/* None */0, /* None */0, CreatePage.make(/* array */[]));
              break;
          
        }
      } else {
        tmp = ReasonReact.element(/* None */0, /* None */0, DetailPage.make(match[0], /* array */[]));
      }
      return React.createElement("div", {
                  className: "fl w-100 pl4 pr4"
                }, ReasonReact.element(/* None */0, /* None */0, Nav.make(/* array */[])), tmp);
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* route : FeedPage */0];
    });
  newrecord[/* reducer */12] = reducer;
  newrecord[/* subscriptions */13] = (function (self) {
      return /* :: */[
              /* Sub */[
                (function () {
                    return ReasonReact.Router[/* watchUrl */1]((function (url) {
                                  return Curry._1(self[/* send */3], /* ChangeRoute */[routeFromUrl(url)]);
                                }));
                  }),
                ReasonReact.Router[/* unwatchUrl */2]
              ],
              /* [] */0
            ];
    });
  return newrecord;
}

exports.reducer = reducer;
exports.routeFromUrl = routeFromUrl;
exports.component = component;
exports.ste = ste;
exports.make = make;
/* component Not a pure module */
