// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Js_json = require("bs-platform/lib/js/js_json.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var ReasonApollo = require("reason-apollo/lib/js/src/ReasonApollo.bs.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var Graphql_error = Caml_exceptions.create("CreatePostButton.CreatePost.Graphql_error");

var query = "mutation CreatePostMutation($text: String!, $title: String!)  {\ncreateDraft(text: $text, title: $title)  {\nid  \ntitle  \ntext  \n}\n}";

function parse(value) {
  var match = Js_json.decodeObject(value);
  if (match) {
    var value$1 = match[0]["createDraft"];
    var match$1 = Js_json.decodeNull(value$1);
    var tmp;
    if (match$1) {
      tmp = /* None */0;
    } else {
      var match$2 = Js_json.decodeObject(value$1);
      var tmp$1;
      if (match$2) {
        var value$2 = match$2[0];
        var value$3 = value$2["id"];
        var match$3 = Js_json.decodeString(value$3);
        var tmp$2;
        if (match$3) {
          tmp$2 = match$3[0];
        } else {
          throw Graphql_error;
        }
        var value$4 = value$2["title"];
        var match$4 = Js_json.decodeString(value$4);
        var tmp$3;
        if (match$4) {
          tmp$3 = match$4[0];
        } else {
          throw Graphql_error;
        }
        var value$5 = value$2["text"];
        var match$5 = Js_json.decodeString(value$5);
        var tmp$4;
        if (match$5) {
          tmp$4 = match$5[0];
        } else {
          throw Graphql_error;
        }
        tmp$1 = {
          id: tmp$2,
          title: tmp$3,
          text: tmp$4
        };
      } else {
        throw Graphql_error;
      }
      tmp = /* Some */[tmp$1];
    }
    return {
            createDraft: tmp
          };
  } else {
    throw Graphql_error;
  }
}

function json_of_optional(encoder, value) {
  if (value) {
    return Curry._1(encoder, value[0]);
  } else {
    return null;
  }
}

function json_of_array(encoder, value) {
  return value.map(Curry.__1(encoder));
}

function json_of_String(value) {
  return value;
}

function make(text, title, _) {
  return {
          query: query,
          variables: Js_dict.fromList(/* :: */[
                /* tuple */[
                  "text",
                  text
                ],
                /* :: */[
                  /* tuple */[
                    "title",
                    title
                  ],
                  /* [] */0
                ]
              ]),
          parse: parse
        };
}

function makeWithVariables(variables) {
  var text = variables.text;
  var title = variables.title;
  return {
          query: query,
          variables: Js_dict.fromList(/* :: */[
                /* tuple */[
                  "text",
                  text
                ],
                /* :: */[
                  /* tuple */[
                    "title",
                    title
                  ],
                  /* [] */0
                ]
              ]),
          parse: parse
        };
}

function ret_type() {
  return /* module */[];
}

var MT_Ret = /* module */[];

var CreatePost = /* module */[
  /* Graphql_error */Graphql_error,
  /* query */query,
  /* parse */parse,
  /* json_of_optional */json_of_optional,
  /* json_of_array */json_of_array,
  /* json_of_String */json_of_String,
  /* make */make,
  /* makeWithVariables */makeWithVariables,
  /* ret_type */ret_type,
  /* MT_Ret */MT_Ret
];

var CreatePostMutation = ReasonApollo.CreateMutation([
      query,
      parse
    ]);

var component = ReasonReact.statelessComponent("CreatePostButton");

function make$1(text, title, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var createPostMutation = make(text, title, /* () */0);
      return ReasonReact.element(/* None */0, /* None */0, Curry._4(CreatePostMutation[/* make */4], /* None */0, /* None */0, /* None */0, (function (mutation, _) {
                        return React.createElement("input", {
                                    className: "pa3 bg-black-10",
                                    type: "submit",
                                    value: "Create",
                                    onClick: (function () {
                                        Curry._3(mutation, /* Some */[createPostMutation.variables], /* Some */[/* array */["getDraftsQuery"]], /* () */0);
                                        ReasonReact.Router[/* push */0]("/drafts");
                                        console.log("SEND");
                                        return /* () */0;
                                      })
                                  });
                      })));
    });
  return newrecord;
}

exports.CreatePost = CreatePost;
exports.CreatePostMutation = CreatePostMutation;
exports.component = component;
exports.make = make$1;
/* CreatePostMutation Not a pure module */
