// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Link = require("./Link.js");
var Utils = require("../Utils.js");
var React = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Post");

function make(isDraft, post, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var match = +(isDraft === true);
      var title = match !== 0 ? Utils.ste(post.title) : Utils.ste(post.title + " (Draft)");
      console.log(title);
      return ReasonReact.element(/* None */0, /* None */0, Link.make("/post/" + post.id, "no-underline ma1", /* array */[
                      React.createElement("h2", {
                            className: "f3 black-80 fw4 lh-solid"
                          }, title),
                      React.createElement("p", {
                            className: "black-80 fw3"
                          }, Utils.ste(post.text))
                    ]));
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
